const canvas = document.getElementById('particleCanvas');
const ctx = canvas.getContext('2d');
const state = { density: 68, speed: 42, size: 3, glow: 24, color: '#f5f0e8', pointer: true, lowPerf: false, seed: 23, preset: 'midnight' };
const presets = { midnight:{density:68,speed:42,size:3,glow:24,color:'#f5f0e8',bg:'#131516'}, milk:{density:57,speed:30,size:3,glow:12,color:'#242628',bg:'#eeebe3'}, signal:{density:78,speed:66,size:2,glow:48,color:'#ff6741',bg:'#17191a'} };
let particles=[], width=0,height=0,dpr=1,pointer={x:-9999,y:-9999,active:false}, raf;
const $ = id => document.getElementById(id);
function hash(seed,x,y){const n=Math.sin(seed*.0001+x*127.1+y*311.7)*43758.5453;return n-Math.floor(n)}
function resize(){const r=canvas.getBoundingClientRect(); dpr=Math.min(2,window.devicePixelRatio||1); width=r.width;height=r.height;canvas.width=Math.floor(width*dpr);canvas.height=Math.floor(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0); $('canvasSize').textContent=`${Math.round(width)} × ${Math.round(height)}`; build()}
function build(){particles=[]; const gap=state.lowPerf?11:9; const cols=Math.ceil(width/gap)+1, rows=Math.ceil(height/gap)+1; for(let y=0;y<rows;y++) for(let x=0;x<cols;x++){const edge=cols*(.04+hash(state.seed,401,Math.floor(y/5))*.24);const edgeDensity=Math.min(1,Math.max(.08,(x-edge+2)/4));const scatter=hash(state.seed,x,y);if(scatter>.78*edgeDensity)continue;particles.push({x:x*gap+4,y:y*gap+4,scatter,phase:hash(state.seed,x+131,y+211)*Math.PI*2,period:3.8+hash(state.seed,x+47,y+73)*4.4,depth:.65+hash(state.seed,x+307,y+419)*.35,seedX:x,seedY:y})} $('particleCount').textContent=`${particles.length.toString().padStart(2,'0')},${String(particles.length*2).padStart(3,'0')} PARTICLES`}
function draw(t){ctx.clearRect(0,0,width,height);const sec=t/1000;const rgb=hexRgb(state.color); for(const p of particles){const reveal=1;let breath=(1-Math.cos(sec*state.speed/42*Math.PI*2/p.period+p.phase))/2;let alpha=(.18+.46*(p.x/Math.max(width,1)/1.1))*(.88+(breath-.5)*.7*p.depth*(state.speed/100))*reveal;if(state.pointer&&pointer.active){const dx=p.x-pointer.x,dy=p.y-pointer.y,dist=Math.hypot(dx,dy);if(dist<180){const force=(1-dist/180)**2*.9;p.x+=(dx/dist||0)*force;p.y+=(dy/dist||0)*force}}const s=state.size*(.42+(p.scatter/.78)*.2)*(0.9+breath*.12);if(state.glow>0){ctx.shadowBlur=state.glow/5;ctx.shadowColor=state.color}ctx.fillStyle=`rgba(${rgb.join(',')},${Math.max(.03,Math.min(.9,alpha))})`;ctx.fillRect(p.x-s/2,p.y-s/2,s,s)}ctx.shadowBlur=0;raf=requestAnimationFrame(draw)}
function hexRgb(hex){const v=hex.replace('#','');return [parseInt(v.slice(0,2),16),parseInt(v.slice(2,4),16),parseInt(v.slice(4,6),16)]}
function apply(){['density','speed','size','glow'].forEach(id=>$(id).value=state[id]);$('densityValue').textContent=state.density+'%';$('speedValue').textContent=state.speed+'%';$('sizeValue').textContent=state.size+' px';$('glowValue').textContent=state.glow+'%';$('particleColor').value=state.color;$('colorValue').textContent=state.color.toUpperCase();canvas.parentElement.style.background=presets[state.preset]?.bg||'#131516';document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.preset===state.preset));build();updateCode()}
function updateCode(){const c=`const canvas = document.querySelector('#particle-canvas');\nconst ctx = canvas.getContext('2d');\nconst color = '${state.color}';\nconst density = ${state.density / 100};\nconst speed = ${state.speed / 100};\n\nfunction random(seed, x, y) {\n  const value = Math.sin(seed * 0.0001 + x * 127.1 + y * 311.7) * 43758.5453;\n  return value - Math.floor(value);\n}\n\n// deterministic grid + soft breathing motion\nfunction paint(time) {\n  ctx.clearRect(0, 0, canvas.width, canvas.height);\n  particles.forEach((p) => {\n    const breath = (1 - Math.cos(time * speed + p.phase)) / 2;\n    const alpha = (0.18 + p.x / canvas.width * 0.46) * density;\n    ctx.fillStyle = hexToRgba(color, alpha * (0.9 + breath * 0.1));\n    ctx.fillRect(p.x, p.y, ${state.size}, ${state.size});\n  });\n  requestAnimationFrame(paint);\n}\npaint(0);`; $('codeOutput').innerHTML=escapeHtml(c).replace(/(const|function|return|forEach|new)/g,'<span class="key">$1</span>').replace(/(random|paint|fillRect|requestAnimationFrame)/g,'<span class="fn">$1</span>').replace(/(0\.\d+|\d+\.\d+)/g,'<span class="num">$1</span>')}
function escapeHtml(s){return s.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function copy(text,btn){navigator.clipboard?.writeText(text);const original=btn.innerHTML;btn.innerHTML='已复制 ✓';setTimeout(()=>btn.innerHTML=original,1400)}
['density','speed','size','glow'].forEach(id=>$(id).addEventListener('input',e=>{state[id]=+e.target.value;apply()}));$('particleColor').addEventListener('input',e=>{state.color=e.target.value;apply()});$('pointerToggle').addEventListener('click',()=>{state.pointer=!state.pointer;$('pointerToggle').classList.toggle('on',state.pointer)});$('perfToggle').addEventListener('click',()=>{state.lowPerf=!state.lowPerf;$('perfToggle').classList.toggle('on',state.lowPerf);build()});document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{state.preset=b.dataset.preset;Object.assign(state,presets[state.preset]);apply()}));document.querySelectorAll('[data-preset-card]').forEach(b=>b.addEventListener('click',()=>{state.preset=b.dataset.presetCard;Object.assign(state,presets[state.preset]);apply();location.hash='playground'}));$('randomize').addEventListener('click',()=>{state.seed=Math.floor(Math.random()*10000);state.density=20+Math.floor(Math.random()*80);state.speed=Math.floor(Math.random()*80);state.size=1+Math.floor(Math.random()*6);state.glow=Math.floor(Math.random()*55);apply()});$('copyAll').addEventListener('click',()=>copy(document.getElementById('codeOutput').textContent,$('copyAll')));$('downloadConfig').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='driftfield-config.json';a.click();URL.revokeObjectURL(a.href)});canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=e.clientX-r.left;pointer.y=e.clientY-r.top;pointer.active=true});canvas.addEventListener('pointerleave',()=>pointer.active=false);window.addEventListener('resize',resize);resize();requestAnimationFrame(draw);
function makeMini(el,preset){const c=document.createElement('canvas');c.width=500;c.height=260;c.style.width='100%';c.style.height='100%';el.append(c);const x=c.getContext('2d'),p=presets[preset];x.fillStyle=p.bg;x.fillRect(0,0,c.width,c.height);const rgb=hexRgb(p.color);for(let y=0;y<29;y++)for(let xx=0;xx<56;xx++){if(hash(23,xx,y)>.6)continue;const a=.15+.55*(xx/56);x.fillStyle=`rgba(${rgb.join(',')},${a})`;const s=1.2+hash(23,xx+3,y+5)*2.5;x.fillRect(xx*9+4,y*9+5,s,s)}}document.querySelectorAll('[data-mini]').forEach(el=>makeMini(el,el.dataset.mini));
